# newest version docker 
version: '3'

services:
  server:
    build: ./server
    container_name: server
    volumes:
      - ./server:/app
    ports:
      - 5000:8000
    restart: always
  react-production:
    container_name: react-production
    build:
      context: ./react-production
      dockerfile: Dockerfile
    ports:
      - 120:80
    depends_on:
      - server
    restart: always
  next-production:
    container_name: next-production
    build: 
      context: ./next-production
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - server
    restart: always