# newest version docker 
version: '3'

services:
  server:
    build: ./server
    container_name: server
    volumes:
      - ./server:/app
    ports:
      - 5000:8000
    restart: always
    networks:
      - example-net
  react-production:
    container_name: react-production
    build:
      context: ./react-production
      dockerfile: Dockerfile
    ports:
      - 120:80
    volumes:
      - .:/app
    depends_on:
      - server
    restart: always
    networks:
      - example-net
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    hostname: nginx
    ports:
      - "80:80" 
    depends_on:
      - server
    networks:
      - example-net  
networks:
  example-net:
    external: true