  name: learn_github

  on:
    push:
      branches: [ main ]
  jobs:
    docker:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          
        - name: Docker Login
          uses: docker/login-action@v1
          with:
            username: ${{ serects.DOCKERHUB_USERNAME }}
            password: ${{ serects.DOCKERHUB_TOKEN }}